artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/presiZHai/datasets/blob/main/LLM-Text-Detection-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\LLM-Text-Detection-data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts\data_ingestion\LLM-Text-Detection-data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  x_test_path: artifacts/data_transformation/x_test.csv
  x_train_path: artifacts/data_transformation/x_train.csv
  y_test_encoded_path: artifacts\data_transformation\y_test_encoded.csv
  y_train_encoded_path: artifacts\data_transformation\y_train_encoded.csv
  model_name: model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.h5
  metric_file_name: artifacts/model_evaluation/metrics.json